"""Database access. SQLite by default (data/courier.db); Postgres/Supabase when DATABASE_URL is set.

Write SQL with `?` placeholders - they're converted for Postgres automatically.
"""
import atexit
import sqlite3
import time
from contextlib import contextmanager

from .config import DATABASE_URL, DB_PATH

IS_POSTGRES = DATABASE_URL.startswith(("postgres://", "postgresql://"))

# ---------- SQLite schema (base + migrations) ----------

SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('customer', 'rider')),
    password_hash TEXT NOT NULL,
    vehicle TEXT,
    plate TEXT,
    is_online INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
    token TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY,
    customer_id INTEGER NOT NULL REFERENCES users(id),
    rider_id INTEGER REFERENCES users(id),
    status TEXT NOT NULL CHECK (status IN ('requested', 'accepted', 'picked_up', 'delivered', 'cancelled')),
    pickup_address TEXT NOT NULL,
    pickup_lat REAL NOT NULL,
    pickup_lng REAL NOT NULL,
    dropoff_address TEXT NOT NULL,
    dropoff_lat REAL NOT NULL,
    dropoff_lng REAL NOT NULL,
    stops_json TEXT NOT NULL DEFAULT '[]',
    tasks_json TEXT NOT NULL DEFAULT '[]',
    recipient_name TEXT,
    recipient_phone TEXT,
    notes TEXT,
    distance_km REAL NOT NULL,
    duration_min REAL NOT NULL,
    route_json TEXT NOT NULL DEFAULT '[]',
    route_source TEXT,
    price REAL NOT NULL,
    currency TEXT NOT NULL,
    breakdown_json TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL,
    accepted_at TEXT,
    picked_up_at TEXT,
    delivered_at TEXT,
    cancelled_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_rider ON orders(rider_id);

CREATE TABLE IF NOT EXISTS rider_locations (
    rider_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    lat REAL NOT NULL,
    lng REAL NOT NULL,
    updated_at TEXT NOT NULL
);
"""

# Schema changes, applied in order on startup. Each runs once (tracked by PRAGMA user_version).
MIGRATIONS = [
    # 1: admin role, rider approval, account suspension, payments, editable settings
    """
    PRAGMA foreign_keys = OFF;
    BEGIN;
    CREATE TABLE users_new (
        id INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        phone TEXT NOT NULL,
        role TEXT NOT NULL CHECK (role IN ('customer', 'rider', 'admin')),
        password_hash TEXT NOT NULL,
        vehicle TEXT,
        plate TEXT,
        is_online INTEGER NOT NULL DEFAULT 0,
        approved INTEGER NOT NULL DEFAULT 1,
        active INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL
    );
    INSERT INTO users_new (id, name, email, phone, role, password_hash, vehicle, plate, is_online, created_at)
        SELECT id, name, email, phone, role, password_hash, vehicle, plate, is_online, created_at FROM users;
    DROP TABLE users;
    ALTER TABLE users_new RENAME TO users;

    ALTER TABLE orders ADD COLUMN payment_method TEXT NOT NULL DEFAULT 'cash';
    ALTER TABLE orders ADD COLUMN payment_status TEXT NOT NULL DEFAULT 'unpaid';
    ALTER TABLE orders ADD COLUMN mmg_number TEXT;
    ALTER TABLE orders ADD COLUMN cancelled_by TEXT;
    UPDATE orders SET payment_status = 'paid' WHERE status = 'delivered';

    CREATE TABLE payments (
        id INTEGER PRIMARY KEY,
        order_id INTEGER NOT NULL REFERENCES orders(id),
        provider TEXT NOT NULL,
        amount REAL NOT NULL,
        currency TEXT NOT NULL,
        status TEXT NOT NULL CHECK (status IN ('pending', 'paid', 'failed', 'refunded', 'void')),
        provider_ref TEXT,
        message TEXT,
        raw_json TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    );
    CREATE INDEX idx_payments_order ON payments(order_id);
    CREATE UNIQUE INDEX idx_payments_ref ON payments(provider, provider_ref);

    CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
    PRAGMA user_version = 1;
    COMMIT;
    PRAGMA foreign_keys = ON;
    """,
    # 2: orders cancelled before payments existed owe nothing
    """
    BEGIN;
    UPDATE orders SET payment_status = 'void' WHERE status = 'cancelled' AND payment_status = 'unpaid';
    PRAGMA user_version = 2;
    COMMIT;
    """,
]

# ---------- Postgres schema (same tables as SQLite after all migrations) ----------

PG_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('customer', 'rider', 'admin')),
    password_hash TEXT NOT NULL,
    vehicle TEXT,
    plate TEXT,
    is_online INTEGER NOT NULL DEFAULT 0,
    approved INTEGER NOT NULL DEFAULT 1,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES users(id),
    rider_id BIGINT REFERENCES users(id),
    status TEXT NOT NULL CHECK (status IN ('requested', 'accepted', 'picked_up', 'delivered', 'cancelled')),
    pickup_address TEXT NOT NULL,
    pickup_lat DOUBLE PRECISION NOT NULL,
    pickup_lng DOUBLE PRECISION NOT NULL,
    dropoff_address TEXT NOT NULL,
    dropoff_lat DOUBLE PRECISION NOT NULL,
    dropoff_lng DOUBLE PRECISION NOT NULL,
    stops_json TEXT NOT NULL DEFAULT '[]',
    tasks_json TEXT NOT NULL DEFAULT '[]',
    recipient_name TEXT,
    recipient_phone TEXT,
    notes TEXT,
    distance_km DOUBLE PRECISION NOT NULL,
    duration_min DOUBLE PRECISION NOT NULL,
    route_json TEXT NOT NULL DEFAULT '[]',
    route_source TEXT,
    price DOUBLE PRECISION NOT NULL,
    currency TEXT NOT NULL,
    breakdown_json TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL,
    accepted_at TEXT,
    picked_up_at TEXT,
    delivered_at TEXT,
    cancelled_at TEXT,
    payment_method TEXT NOT NULL DEFAULT 'cash',
    payment_status TEXT NOT NULL DEFAULT 'unpaid',
    mmg_number TEXT,
    cancelled_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_rider ON orders(rider_id);
CREATE TABLE IF NOT EXISTS rider_locations (
    rider_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    provider TEXT NOT NULL,
    amount DOUBLE PRECISION NOT NULL,
    currency TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('pending', 'paid', 'failed', 'refunded', 'void')),
    provider_ref TEXT,
    message TEXT,
    raw_json TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_payments_order ON payments(order_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_ref ON payments(provider, provider_ref);
CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
-- Supabase publishes tables in "public" through its Data API. RLS with no policies blocks that route;
-- this app connects as the database owner, which bypasses RLS.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE rider_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY
"""

# ---------- connections ----------

_pool = None
_last_used = {}      # id(connection) -> time it was last returned to the pool
IDLE_CHECK_SECONDS = 20


def _check_if_idle(conn):
    """Ping a pooled connection only if it has sat idle (hosted poolers drop idle connections).

    Every network round trip to a hosted database costs real time, so busy connections skip the ping.
    """
    from psycopg_pool import ConnectionPool
    if time.monotonic() - _last_used.get(id(conn), 0) > IDLE_CHECK_SECONDS:
        ConnectionPool.check_connection(conn)


def _pg_pool():
    global _pool
    if _pool is None:
        from psycopg.rows import dict_row
        from psycopg_pool import ConnectionPool
        # autocommit: a single statement is one round trip (no BEGIN/COMMIT); execute_all opens a transaction.
        # prepare_threshold=None: Supabase's transaction pooler doesn't support prepared statements.
        _pool = ConnectionPool(
            DATABASE_URL, min_size=1, max_size=10, open=True, check=_check_if_idle,
            kwargs={"row_factory": dict_row, "prepare_threshold": None, "autocommit": True},
        )
        atexit.register(_pool.close)
    return _pool


def _sql(sql):
    return sql.replace("?", "%s") if IS_POSTGRES else sql


@contextmanager
def connection():
    """A database connection. SQLite commits when the block succeeds; Postgres runs in autocommit."""
    if IS_POSTGRES:
        with _pg_pool().connection() as conn:
            try:
                yield conn
            finally:
                _last_used[id(conn)] = time.monotonic()
        return
    conn = sqlite3.connect(DB_PATH, timeout=10)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        with conn:
            yield conn
    finally:
        conn.close()


def init():
    if IS_POSTGRES:
        with connection() as conn:
            for statement in PG_SCHEMA.split(";"):
                if statement.strip():
                    conn.execute(statement)
        return
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(DB_PATH, timeout=10)
    try:
        conn.execute("PRAGMA journal_mode = WAL")
        conn.executescript(SCHEMA)
        conn.commit()
        version = conn.execute("PRAGMA user_version").fetchone()[0]
        for script in MIGRATIONS[version:]:
            conn.executescript(script)
    finally:
        conn.close()


def query(sql, args=()):
    with connection() as conn:
        return [dict(r) for r in conn.execute(_sql(sql), args).fetchall()]


def query_one(sql, args=()):
    rows = query(sql, args)
    return rows[0] if rows else None


def execute(sql, args=()):
    """Run a write. Returns the number of rows changed."""
    with connection() as conn:
        return conn.execute(_sql(sql), args).rowcount


def insert(sql, args=()):
    """Run an INSERT. Returns the new row's id."""
    with connection() as conn:
        if IS_POSTGRES:
            return conn.execute(_sql(sql) + " RETURNING id", args).fetchone()["id"]
        return conn.execute(sql, args).lastrowid


def execute_all(statements):
    """Run several writes in one transaction: [(sql, args), ...]."""
    with connection() as conn:
        if IS_POSTGRES:
            with conn.transaction():
                for sql, args in statements:
                    conn.execute(_sql(sql), args)
            return
        for sql, args in statements:
            conn.execute(sql, args)


def user_for_token(token):
    if not token:
        return None
    return query_one(
        "SELECT u.* FROM sessions s JOIN users u ON u.id = s.user_id WHERE s.token = ? AND u.active = 1", (token,)
    )
